var allAnimals = {"name":"AnimalCrawlerNewest","count":11,"frequency":"Manual Crawl","version":3,
"newdata":true,"lastrunstatus":"success","thisversionstatus":"success","thisversionrun":"Sun Jun 21 2015 02:48:11 GMT+0000 (UTC)",


	"results":{
		"collection1":[
			//a
			{	
				//0
				"AnimalName":"Aardvark",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Orycteropodidae","text":"Tubulidentata"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Orycteropodidae","text":"Orycteropodidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Orycteropus","text":"Orycteropus"},
				"Species":"O. afer",
				"Image":{"alt":"Porc formiguer.JPG","href":"https://en.wikipedia.org/wiki/File:Porc_formiguer.JPG",
				"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Porc_formiguer.JPG/220px-Porc_formiguer.JPG","text":""},
				"index":1,"url":"https://en.wikipedia.org/wiki/Aardvark"},

			{	
				//1
				"AnimalName":"African bush elephant",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Proboscidea","text":"Proboscidea"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Elephantidae","text":"Elephantidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Loxodonta","text":"Loxodonta"},
				"Species":"L. africana","Image":{"alt":"African Bush Elephant.jpg","href":"https://en.wikipedia.org/wiki/File:African_Bush_Elephant.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/African_Bush_Elephant.jpg/220px-African_Bush_Elephant.jpg","text":""},
				"index":8,"url":"https://en.wikipedia.org/wiki/African_bush_elephant"},
			///b
			{
				//2
				"AnimalName":"Bactrian camel",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordata","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Even-toed_ungulate","text":"Artiodactyla"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Camelid","text":"Camelidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Camel","text":"Camelus"},
				"Species":"C. bactrianus","Image":{"alt":"2011 Trampeltier 1528.JPG","href":"https://en.wikipedia.org/wiki/File:2011_Trampeltier_1528.JPG",
				"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/2011_Trampeltier_1528.JPG/250px-2011_Trampeltier_1528.JPG","text":""},
				"index":6,"url":"https://en.wikipedia.org/wiki/Bactrian_camel"},
	
			
			{
				//3
				"AnimalName":"Brown_bear",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Carnivora","text":"Carnivora"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Bear","text":"Ursidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/European_brown_bear","text":"U. arctos arctos"},
				"Species":"U. arctos",
				"Image":{"alt":"Brown bear.jpg","href":"https://en.wikipedia.org/wiki/File:Brown_bear.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Brown_bear.jpg/220px-Brown_bear.jpg","text":""},
				"index":5,"url":"https://en.wikipedia.org/wiki/Brown_bear"},
			//c
			{	
				//4
				"AnimalName":"Capybara",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Rodentia","text":"Rodentia"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Caviidae","text":"Caviidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Hydrochoerus","text":"Hydrochoerus"},
				"Species":"Hydrochoerus hydrochaeris",
				"Image":{"alt":"Capybara_(Hydrochoerus_hydrochaeris).JPG",
				"href":"https://en.wikipedia.org/wiki/Capybara#/media/File:Capybara_(Hydrochoerus_hydrochaeris).JPG",
				"src":"https://upload.wikimedia.org/wikipedia/commons/e/ec/Capybara_%28Hydrochoerus_hydrochaeris%29.JPG"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Capybara"},
			{	
				//4
				"AnimalName":"Chipmunks",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Rodentia","text":"Rodentia"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Sciuridae","text":"Sciuridae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Tamias","text":"Tamias"},
				"Species":"T. minimus",
				"Image":{"alt":"Tamias_minimus.jpg",
				"href":"https://en.wikipedia.org/wiki/Least_chipmunk#/media/File:Tamias_minimus.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/9/94/Tamias_minimus.jpg"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Least_chipmunk"},
			//d	
			{	
				//4
				"AnimalName":"Domestic Cat",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Carnivora","text":"Carnivora"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Felidae","text":"Felidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Felis","text":"Felis"},
				"Species":"F. catus",
				"Image":{"alt":"Gato_enervado_pola_presencia_dun_can.jpg",
				"href":"https://en.wikipedia.org/wiki/Cat#/media/File:Kittyply_edit1.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/b/bb/Kittyply_edit1.jpg"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Cat"},
			
			{	
				"AnimalName":"Deathstalker aka Israeli Yellow Scorpion",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Arthropoda","text":"Arthropoda"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Arachnida","text":"Arachnida"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Scorpiones","text":"Scorpiones"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Buthidae","text":"Buthidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Leiurus","text":"Leiurus"},
				"Species":"L. quinquestriatus",
				"Image":{"alt":"Deathstalker_ST_07.JPG","href":"https://en.wikipedia.org/wiki/Deathstalker#/media/File:Deathstalker_ST_07.JPG",
				"src":"https://upload.wikimedia.org/wikipedia/commons/3/39/Deathstalker_ST_07.JPG","text":""},
				"index":1,"url":"https://en.wikipedia.org/wiki/Deathstalker"},
			
			{
				//5
				"AnimalName":"Donkey",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Odd-toed_ungulate","text":"Perissodactyla"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Equidae","text":"Equidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Equus_(genus)","text":"Equus"},
				"Species":"E. a. asinus",
				"Image":{"alt":"Donkey 1 arp 750px.jpg","href":"https://en.wikipedia.org/wiki/File:Donkey_1_arp_750px.jpg","src":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Donkey_1_arp_750px.jpg/250px-Donkey_1_arp_750px.jpg","text":""},
				"index":2,"url":"https://en.wikipedia.org/wiki/Donkey"},

			//e
			{	
				"AnimalName":"Eastern Grey Kangaroo",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Diprotodontia","text":"Diprotodontia"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Macropodidae","text":"Macropodidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Macropus","text":"Macropus"},
				"Species":"M. giganteus",
				"Image":{"alt":"Macropus_giganteus_Male.jpg",
				"href":"https://en.wikipedia.org/wiki/Eastern_grey_kangaroo#/media/File:Macropus_giganteus_Male.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/e/e2/Macropus_giganteus_Male.jpg","text":"Kangaroo"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Eastern_grey_kangaroo"},
			{	
				//6
				"AnimalName":"Emperor penguin",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Aves","text":"Aves"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Sphenisciformes","text":"Sphenisciformes"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Spheniscidae","text":"Spheniscidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Aptenodytes","text":"Aptenodytes"},
				"Species":"A. forsteri",
				"Image":{"href":"https://en.wikipedia.org/wiki/Emperor_penguin#/media/File:Kaiserpinguine_mit_Jungen.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/2/28/Kaiserpinguine_mit_Jungen.jpg","text":"Pengiun"},
				"index":1,"url":"https://en.wikipedia.org/wiki/Emperor_penguin"},
			//f
			//g 
			{	
				"AnimalName":"Giraffe",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Artiodactyla","text":"Artiodactyla"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Giraffidae","text":"Giraffidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Giraffa","text":"Giraffa"},
				"Species":"T. minimus",
				"Image":{"alt":"Female_Giraffe_Mikumi_National_Park.jpg",
				"href":"https://en.wikipedia.org/wiki/Masai_giraffe#/media/File:Female_Giraffe_Mikumi_National_Park.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/4/49/Female_Giraffe_Mikumi_National_Park.jpg"},
				"index":8,"url":"https://upload.wikimedia.org/wikipedia/commons/4/49/Female_Giraffe_Mikumi_National_Park.jpg"},
				
			
		
			{	"AnimalName":"Giant panda",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Carnivora","text":"Carnivora"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Bear","text":"Ursidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Ailuropoda","text":"Ailuropoda"},
				"Image":{"alt":"Grosser Panda.JPG","href":"https://en.wikipedia.org/wiki/File:Grosser_Panda.JPG","src":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Grosser_Panda.JPG/250px-Grosser_Panda.JPG","text":""},
				"index":10,"url":"https://en.wikipedia.org/wiki/Giant_panda"},
			{	
				"AnimalName":"Golden Jackal",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Carnivora","text":"Carnivora"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Canidae","text":"Canidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Canis","text":"Canis"},
				"Species":"C. aureus",
				"Image":{"alt":"Flickr_-_Rainbirder_-_Golden_Jackal.jpg",
				"href":"https://en.wikipedia.org/wiki/Golden_jackal#/media/File:Flickr_-_Rainbirder_-_Golden_Jackal.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/9/9e/Flickr_-_Rainbirder_-_Golden_Jackal.jpg","text":"Golden Jackal"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Golden_jackal" },
			{	//8
				"AnimalName":"Gray Wolf",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Carnivora","text":"Carnivora"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Canidae","text":"Canidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Canis","text":"Canis"},
				"Species":"C. lupus",
				"Image":{"alt":"European_grey_wolf_in_Prague_zoo.jpg",
				"href":"https://en.wikipedia.org/wiki/Gray_wolf#/media/File:European_grey_wolf_in_Prague_zoo.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/a/ab/European_grey_wolf_in_Prague_zoo.jpg","text":""},
				"index":8,"url":"https://en.wikipedia.org/wiki/Gray_wolf"},
			{	//8
				"AnimalName":"Great White Shark",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Chondrichthyes","text":"Chondrichthyes"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Lamniformes","text":"Lamniformes"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Lamnidae","text":"Lamnidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Carcharodon","text":"Carcharodon"},
				"Species":"White_shark.jpg",
				"Image":{"alt":"White_shark.jpg",
				"href":"https://en.wikipedia.org/wiki/Great_white_shark#/media/File:White_shark.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/5/56/White_shark.jpg","text":"Great White Shark"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Great_white_shark"},

			{	//8
				"AnimalName":"Green Iguana",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Reptilia","text":"Reptilia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Carnivora","text":"Carnivora"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Iguanidae","text":"Iguanidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Iguana","text":"Iguana"},
				"Species":"I. iguana",
				"Image":{"alt":"Green_iguana_(Iguana_iguana).JPG",
				"href":"https://en.wikipedia.org/wiki/Green_iguana#/media/File:Green_iguana_(Iguana_iguana).JPG",
				"src":"https://upload.wikimedia.org/wikipedia/commons/0/05/Green_iguana_%28Iguana_iguana%29.JPG","text":"Green Iguana"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Green_iguana"},
			{
				"AnimalName":"Guinea_Pig",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Rodentia","text":"Rodentia"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Caviidae","text":"Caviidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Cavia","text":"Cavia"},
				"Species":"C. porcellus",
				"Image":{"alt":"Two_adult_Guinea_Pigs_(Cavia_porcellus)","href":"https://en.wikipedia.org/wiki/Guinea_pig#/media/File:Two_adult_Guinea_Pigs_(Cavia_porcellus).jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/0/00/Two_adult_Guinea_Pigs_%28Cavia_porcellus%29.jpg","text":"Guinea_pig"},
				"index":5,"url":"https://en.wikipedia.org/wiki/Guinea_pig"},
			//h
			{	//9
				"AnimalName":"Hamadryas_baboon",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Primate","text":"Primate"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Old_World_monkey","text":"Cercopithecidae "},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Baboon","text":"Papio"},
				"Species":"P. hamadryas",
				"Image":{"alt":"Hamadryas baboon.jpg","href":"https://en.wikipedia.org/wiki/File:Hamadryas_baboon.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Hamadryas_baboon.jpg/220px-Hamadryas_baboon.jpg","text":""},
				"index":3,"url":"https://en.wikipedia.org/wiki/Hamadryas_baboon"},

			{	//10
				"AnimalName":"Honey_badger",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Carnivora","text":"Carnivora"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Mustelidae","text":"Mustelidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Honey_badger","text":"Mellivora"},
				"Species":"Mellivorinae",
				"Image":{"alt":"Honey badger.jpg","href":"https://en.wikipedia.org/wiki/File:Honey_badger.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Honey_badger.jpg/220px-Honey_badger.jpg","text":""},
				"index":4,"url":"https://en.wikipedia.org/wiki/Honey_badger"},
			
			//i
			{	//10
				"AnimalName":"Indri",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Primate","text":"Primate"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Indriidae","text":"Indriidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Indri","text":"Indri"},
				"Species":"Indri indri",
				"Image":{"alt":"Indri_Andasibe.JPG",
				"href":"https://en.wikipedia.org/wiki/Indri#/media/File:Indri_Andasibe.JPG",
				"src":"https://upload.wikimedia.org/wikipedia/commons/e/ea/Indri_Andasibe.JPG","text":"Indri"},
				"index":4,"url":"https://en.wikipedia.org/wiki/Indri"},
			//j

			//k
			{	
				"AnimalName":"Komodo Dragon",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Reptilia","text":"Reptilia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Squamata","text":"Squamata"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Varanidae","text":"Varanidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Varanus","text":"Varanus"},
				"Species":"V. komodoensis",
				"Image":{"alt":"Komodo_dragon_(Varanus_komodoensis).jpg",
				"href":"https://en.wikipedia.org/wiki/Komodo_dragon#/media/File:Komodo_dragon_(Varanus_komodoensis).jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/e/e8/Komodo_dragon_%28Varanus_komodoensis%29.jpg","text":"Komodo Dragon"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Komodo_dragon"},
			{	
				"AnimalName":"Killer Whale",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Cetartiodactyla","text":"Cetartiodactyla"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Delphinidae","text":"Delphinidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Orcinus","text":"Orcinus"},
				"Species":"O. orca",
				"Image":{"alt":"Killerwhales_jumping.jpg",
				"href":"https://en.wikipedia.org/wiki/Killer_whale#/media/File:Killerwhales_jumping.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/3/37/Killerwhales_jumping.jpg","text":"Kangaroo"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Killer_whale"},
			//l
			//l
			{	
				"AnimalName":"Leopard",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Carnivora","text":"Carnivora"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Felidae","text":"Felidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Panthera","text":"Panthera"},
				"Species":"P. pardus",
				"Image":{"alt":"African_Leopard_5.JPG",
				"href":"https://en.wikipedia.org/wiki/Leopard#/media/File:African_Leopard_5.JPG",
				"src":"https://upload.wikimedia.org/wikipedia/commons/0/0b/African_Leopard_5.JPG","text":"Leopard"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Leopard"},
			{	
				"AnimalName":"Lion",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Carnivora","text":"Carnivora"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Felidae","text":"Felidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Panthera","text":"Panthera"},
				"Species":"P. Leo",
				"Image":{"alt":"Lion_waiting_in_Namibia.jpg",
				"href":"https://en.wikipedia.org/wiki/File:FLion_waiting_in_Namibia.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/7/73/Lion_waiting_in_Namibia.jpg","text":""},
				"index":8,"url":"https://en.wikipedia.org/wiki/lion"},
			{
				"AnimalName":"Long-beaked common dolphin",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Cetacea","text":"Cetacea"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Oceanic_dolphin","text":"Delphinidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Common_dolphin","text":"Delphinus"},
				"Species":"D. capensis",
				"Image":{"alt":"Delphinus capensis.JPG",
				"href":"https://en.wikipedia.org/wiki/File:Delphinus_capensis.JPG",
				"src":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Delphinus_capensis.JPG/220px-Delphinus_capensis.JPG","text":""},
				"index":7,"url":"https://en.wikipedia.org/wiki/Long-beaked_common_dolphin"},
			//m
			{	
				"AnimalName":"Mountain Zebra",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Perissodactyla","text":"Perissodactyla"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Equidae","text":"Equidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Equus","text":"Equus"},
				"Species":"Equus zebra",
				"Image":{"alt":"Hartmann_zebra_hobatere_S.jpg",
				"href":"https://en.wikipedia.org/wiki/Mountain_zebra#/media/File:Hartmann_zebra_hobatere_S.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/1/12/Hartmann_zebra_hobatere_S.jpg"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Zebra"},
			{	
				"AnimalName":"Mouse",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Rodentia","text":"Rodentia"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Muridae","text":"Muridae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Mus","text":"Mus"},
				"Species":"Mus musculus",
				"Image":{"alt":"cutebrownmouse.bmp",
				"href":"http://vetmed.duhs.duke.edu/Photos/cutebrownmouse.bmp",
				"src":"http://vetmed.duhs.duke.edu/Photos/cutebrownmouse.bmp"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Mouse"},
			{	
				"AnimalName":"Musk Ox",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Even-toed_ungulate","text":"Artiodactyla"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Bovidae","text":"Bovidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Vulpes","text":"Vulpes"},
				"Species":"VO. moschatus",
				"Image":{"alt":"Ovibos_moschatus_qtl3.jpg",
				"href":"https://en.wikipedia.org/wiki/Muskox#/media/File:Ovibos_moschatus_qtl3.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/e/ed/Ovibos_moschatus_qtl3.jpg","text":""},
				"index":8,"url":"https://en.wikipedia.org/wiki/Muskox"},
			//n
			//o
			//p
			{	
				"AnimalName":"Peafowl",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Aves","text":"Aves"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Galliformes","text":"Galliformes"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Phasianidae","text":"Phasianidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Peafowl","text":"Pavi"},
				"Species":"P. cristatus",
				"Image":{"alt":"Peacock_by_Nihal_Jabin.jpg",
				"href":"https://en.wikipedia.org/wiki/Indian_peafowl#/media/File:Peacock_by_Nihal_Jabin.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/3/39/Peacock_by_Nihal_Jabin.jpg","text":""},
				"index":8,"url":"https://en.wikipedia.org/wiki/Peafowl"},
			{
				"AnimalName":"Peregrine falcon",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Aves","text":"Aves"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Falconidae","text":"Falconiformes"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Falconidae","text":"Falconidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Falcon","text":"Falco"},	
				"Species":"F. peregrinus",
				"Image":{"alt":"Falco peregrinus -Nova Scotia, Canada -eating-8.jpg","href":"https://en.wikipedia.org/wiki/File:Falco_peregrinus_-Nova_Scotia,_Canada_-eating-8.jpg","src":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Falco_peregrinus_-Nova_Scotia%2C_Canada_-eating-8.jpg/220px-Falco_peregrinus_-Nova_Scotia%2C_Canada_-eating-8.jpg","text":""},"index":9,"url":"https://en.wikipedia.org/wiki/Peregrine_falcon"
			},

			{	
				"AnimalName":"Pygmy rabbit",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Lagomorpha","text":"Lagomorpha"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Leporidae","text":"Leporidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Brachylagus","text":"Brachylagus"},
				"Species":"B. idahoensis",
				"Image":{"alt":"BRACHYLAGUS_IDAHOENSIS.jpg",
				"href":"https://en.wikipedia.org/wiki/Pygmy_rabbit#/media/File:BRACHYLAGUS_IDAHOENSIS.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/e/ed/BRACHYLAGUS_IDAHOENSIS.jpg"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Pygmy_rabbit"},
			
			//r
			{	
				"AnimalName":"Racoon",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Carnivora","text":"Carnivora"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Procyonidae","text":"Procyonidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Procyon_(genus)","text":"Procyon"},
				"Species":"	P. lotor",
				"Image":{"alt":"Raccoon_climbing_in_tree_-_Cropped_and_color_corrected.jpg",
				"href":"https://en.wikipedia.org/wiki/Raccoon#/media/File:Raccoon_climbing_in_tree_-_Cropped_and_color_corrected.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/9/9f/Raccoon_climbing_in_tree_-_Cropped_and_color_corrected.jpg"},
				"index":8,"url":"https://en.wikipedia.org/wiki/Raccoon"},
				
			{	
				"AnimalName":"Red Fox",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Carnivora","text":"Carnivora"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Canidae","text":"Canidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Vulpes","text":"Vulpes"},
				"Species":"V. vulpes",
				"Image":{"alt":"Fox_study_6.jpg",
				"href":"https://en.wikipedia.org/wiki/Red_fox#/media/File:Fox_study_6.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/d/df/Fox_study_6.jpg","text":""},
				"index":8,"url":"https://en.wikipedia.org/wiki/Red_fox"},

			{	
				"AnimalName":"Rhinoceros",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Odd-toed_ungulate","text":"Perissodactyla"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Rhinocerotidae","text":"Rhinocerotidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/White_rhinoceros","text":"Ceratotherium"},
				"Species":"Ceratotherium simum",
				"Image":{"alt":"Rhinoc%C3%A9ros_blanc_JHE.jpg",
				"href":"https://en.wikipedia.org/wiki/White_rhinoceros#/media/File:Rhinoc%C3%A9ros_blanc_JHE.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/3/38/Rhinoc%C3%A9ros_blanc_JHE.jpg","text":""},
				"index":8,"url":"https://en.wikipedia.org/wiki/Rhinoceros"},

			//t

			{	
				"AnimalName":"Tiger",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Carnivora","text":"Carnivora"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Felidae","text":"Felidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Panthera","text":"Panthera"},
				"Species":"P. tigris",
				"Image":{"alt":"Tigress_at_Jim_Corbett_National_Park.jpg",
				"href":"https://en.wikipedia.org/?title=Tiger#/media/File:Tigress_at_Jim_Corbett_National_Park.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/5/54/Tigress_at_Jim_Corbett_National_Park.jpg","text":""},
				"index":8,"url":"https://en.wikipedia.org/?title=Tiger"},


			{	
				"AnimalName":"Wild horse",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Odd-toed_ungulate","text":"Perissodactyla"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Equidae","text":"Equidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Equus_(genus)","text":"Equus"},
				"Species":"E. ferus",
				"Image":{"alt":"Prezewalsky 26-9-2004-2.JPG","href":"https://en.wikipedia.org/wiki/File:Prezewalsky_26-9-2004-2.JPG","src":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Prezewalsky_26-9-2004-2.JPG/220px-Prezewalsky_26-9-2004-2.JPG","text":""},
				"index":11,"url":"https://en.wikipedia.org/wiki/Wild_horse"},				
			
			{	
				"AnimalName":"Western Lowland Gorilla",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Primate","text":"Primate"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Old_World_monkey","text":"Hominidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Gorilla","text":"Gorilla"},
				"Species":"G. gorilla",
				"Image":{"alt":"Western_Lowland_Gorilla_Feb09_02.jpg",
				"href":"https://en.wikipedia.org/wiki/Western_gorilla#/media/File:Western_Lowland_Gorilla_Feb09_02.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/d/db/Western_Lowland_Gorilla_Feb09_02.jpg","text":"Gorilla"},
				"index":3,"url":"https://en.wikipedia.org/wiki/Western_gorilla"},
							{	
				"AnimalName":"Yak",
				"Kingdom":{"href":"https://en.wikipedia.org/wiki/Animal","text":"Animalia"},
				"Phylum":{"href":"https://en.wikipedia.org/wiki/Chordate","text":"Chordata"},
				"Class":{"href":"https://en.wikipedia.org/wiki/Mammal","text":"Mammalia"},
				"Order":{"href":"https://en.wikipedia.org/wiki/Artiodactyla","text":"Artiodactyla"},
				"Family":{"href":"https://en.wikipedia.org/wiki/Bovidae","text":"Bovidae"},
				"Genus":{"href":"https://en.wikipedia.org/wiki/Bos","text":"Bos"},
				"Species":"Bos grunniens",
				"Image":{"alt":"Bos_grunniens_at_Letdar_on_Annapurna_Circuit.jpg",
				"href":"https://en.wikipedia.org/wiki/Yak#/media/File:Bos_grunniens_at_Letdar_on_Annapurna_Circuit.jpg",
				"src":"https://upload.wikimedia.org/wikipedia/commons/0/0e/Bos_grunniens_at_Letdar_on_Annapurna_Circuit.jpg","text":"Yak"},
				"index":3,"url":"https://en.wikipedia.org/wiki/Yak"},


		]}}